package com.liner.graduationproject.db.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liner.graduationproject.db.bean.User;
import com.liner.graduationproject.db.bean.ScenicSpot;
import com.liner.graduationproject.db.bean.ReturnMsg;

import com.liner.graduationproject.db.bean.UserDao;
import com.liner.graduationproject.db.bean.ScenicSpotDao;
import com.liner.graduationproject.db.bean.ReturnMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig scenicSpotDaoConfig;
    private final DaoConfig returnMsgDaoConfig;

    private final UserDao userDao;
    private final ScenicSpotDao scenicSpotDao;
    private final ReturnMsgDao returnMsgDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        scenicSpotDaoConfig = daoConfigMap.get(ScenicSpotDao.class).clone();
        scenicSpotDaoConfig.initIdentityScope(type);

        returnMsgDaoConfig = daoConfigMap.get(ReturnMsgDao.class).clone();
        returnMsgDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        scenicSpotDao = new ScenicSpotDao(scenicSpotDaoConfig, this);
        returnMsgDao = new ReturnMsgDao(returnMsgDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(ScenicSpot.class, scenicSpotDao);
        registerDao(ReturnMsg.class, returnMsgDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        scenicSpotDaoConfig.clearIdentityScope();
        returnMsgDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ScenicSpotDao getScenicSpotDao() {
        return scenicSpotDao;
    }

    public ReturnMsgDao getReturnMsgDao() {
        return returnMsgDao;
    }

}
