package com.liner.graduationproject.db.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RETURN_MSG".
*/
public class ReturnMsgDao extends AbstractDao<ReturnMsg, Long> {

    public static final String TABLENAME = "RETURN_MSG";

    /**
     * Properties of entity ReturnMsg.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ScenicSpot = new Property(1, String.class, "scenicSpot", false, "SCENIC_SPOT");
        public final static Property Addr = new Property(2, String.class, "Addr", false, "ADDR");
        public final static Property Classify = new Property(3, String.class, "classify", false, "CLASSIFY");
    }


    public ReturnMsgDao(DaoConfig config) {
        super(config);
    }
    
    public ReturnMsgDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RETURN_MSG\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SCENIC_SPOT\" TEXT," + // 1: scenicSpot
                "\"ADDR\" TEXT," + // 2: Addr
                "\"CLASSIFY\" TEXT);"); // 3: classify
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RETURN_MSG\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ReturnMsg entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String scenicSpot = entity.getScenicSpot();
        if (scenicSpot != null) {
            stmt.bindString(2, scenicSpot);
        }
 
        String Addr = entity.getAddr();
        if (Addr != null) {
            stmt.bindString(3, Addr);
        }
 
        String classify = entity.getClassify();
        if (classify != null) {
            stmt.bindString(4, classify);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ReturnMsg entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String scenicSpot = entity.getScenicSpot();
        if (scenicSpot != null) {
            stmt.bindString(2, scenicSpot);
        }
 
        String Addr = entity.getAddr();
        if (Addr != null) {
            stmt.bindString(3, Addr);
        }
 
        String classify = entity.getClassify();
        if (classify != null) {
            stmt.bindString(4, classify);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ReturnMsg readEntity(Cursor cursor, int offset) {
        ReturnMsg entity = new ReturnMsg( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // scenicSpot
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Addr
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // classify
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ReturnMsg entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setScenicSpot(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAddr(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setClassify(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ReturnMsg entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ReturnMsg entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ReturnMsg entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
